### ISSUE TITLE
libtbb.so.12

### ISSUE THREAD

**Issue by ChenLu-china** [sxysxy/OIDN-python#6]
I meet the problem is:
Traceback (most recent call last):
  File "/home/chenlu/miniconda3/envs/pytorch111/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/chenlu/miniconda3/envs/pytorch111/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/chenlu/.vscode/extensions/ms-python.debugpy-2024.6.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/chenlu/.vscode/extensions/ms-python.debugpy-2024.6.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/chenlu/.vscode/extensions/ms-python.debugpy-2024.6.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 317, in run_module
    run_module_as_main(options.target, alter_argv=True)
  File "/home/chenlu/.vscode/extensions/ms-python.debugpy-2024.6.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 229, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/chenlu/.vscode/extensions/ms-python.debugpy-2024.6.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 186, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/chenlu/.vscode/extensions/ms-python.debugpy-2024.6.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 150, in _get_module_details
    __import__(pkg_name)
  File "/home/chenlu/chenlu/ezone/image_denoising/OIDN-python/oidn/__init__.py", line 45, in <module>
    __lib_oidn = __load_lib()
  File "/home/chenlu/chenlu/ezone/image_denoising/OIDN-python/oidn/__init__.py", line 19, in __load_lib
    ctypes.CDLL(os.path.join(cur_path, f"lib.linux.x64/libOpenImageDenoise_device_cpu.so.{oidn_version}"))
  File "/home/chenlu/miniconda3/envs/pytorch111/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libtbb.so.12: ELF load command address/offset not properly aligned

**Comment by sxysxy** [comment]
不太好解决，似乎是因为你系统的ld-linux版本太低（这通常是因为linux发行版版本比较低），但是我们这个作为一个库而非直接可执行程序，没法附带高版本的ld-linux解释器一起发行。
